### ISSUE TITLE
Pintrest details view animation

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuse-samples#13]
Something like this:
https://engineering.pinterest.com/sites/default/files/article/fields/field_image/Transition-Small.gif

**Comment by helderaraujo** [comment]
I've been trying to do exactly that on fuse. +1

**Comment by raphaelgodoi** [comment]
@helderaraujo que bom que temos um Brasileiro também pra fazer isso.. você esta no slack do fuse? poderiamos conversar por lá?

**Comment by raphaelgodoi** [comment]
I think the example must be like the last version of pinterest. +1
