### ISSUE TITLE
AmazonS3 example crashes on Android

### ISSUE THREAD

**Issue by kristianhasselknippe** [fusetools/fuse-samples#22]
I updated it to expose its service as a JS API, but it crashes on Android.

When fixed, please add it back to the README index.

**Comment by kristianhasselknippe** [comment]
https://github.com/fusetools/fuse-samples/commit/0bb6deb5ba5e2694f3c4328ccb9d77759846c0c5

**Comment by ollef** [comment]
It works here. I'll need some more info, please!

**Comment by kristianhasselknippe** [comment]
sorry @ollef , i'm being stupid. Messed up the setup

**Comment by ollef** [comment]
Cool, no worries! :)
